id = "gato-theme"
name = "Gato Theme"
description = "A dark theme using Gato OS colorscheme"
version = "0.1.0"
schema_version = 1
authors = ["DCCXXV"]
repository = "https://github.com/DCCXXV/gato-zed"
